INSERT INTO public.users(id,
                         created_at,
                         updated_at,
                         email,
                         failed_login_attempts,
                         lock_time,
                         name,
                         password,
                         phone_number,
                         role)
VALUES (9999999,
        now(),
        now(),
        'integration_test@example.com',
        0,
        null,
        'integration_test_user',
        '$2y$10$eV7Ow8iuVQoPi3IFCZoI0u0UwwdzTt6p.Wa7CwyPU3ZEpj85q3Oly', -- password1234567890
        '00000000000',
        'USER');

INSERT INTO public.restaurants(id,
                               created_at,
                               updated_at,
                               cuisine_type,
                               image_path,
                               location,
                               name,
                               reception_end_time,
                               reception_start_time)
VALUES (9999999,
        now(),
        now(),
        '和食',
        '',
        '大阪府',
        'integration_test_restaurant',
        '15:00:00',
        '23:00:00');

INSERT INTO public.seat_details(id,
                                created_at,
                                updated_at,
                                duration,
                                number_of_seats,
                                person_per_seat,
                                restaurant_id)
VALUES (9999999,
        now(),
        now(),
        60,
        2,
        4,
        9999999);